language: node_js
node_js:
  - '10'

before_deploy:
  - yarn generate
deploy:
  provider: pages
  skip-cleanup: true
  keep_history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  name: TSUYUSATO Kitsune
  email: make.just.on+ci@gmail.com
  on:
    branch: master
