language: node_js
node_js:
  - '10'

script:
  - yarn test
  - yarn lint

before_deploy:
  - yarn generate

deploy:
  provider: pages
  skip-cleanup: true
  keep_history: true
  target-branch: release
  github-token: "$GITHUB_TOKEN"
  local-dir: dist
  name: TSUYUSATO Kitsune
  email: make.just.on@gmail.com
  on:
    branch: master

notifications:
  slack:
    secure: m1U8a9zITJ5onGFmerJ3F1j4Da3ZPRX8sBIq4J21Y9FTZWhIlNogW38yCU3FM6/4DDt7S7N+9Odv3gqYq9NaTnOtJC5Et7MMRoVDmuzHgYOdcZ/g4TKYwNgiiVOG3Se64Y9wZE9lc5Hd97Yo2MzuDtClg+H+J/AsJ8eDh6p0bb7JFQkuf8sj93nspFcElSRksUqL48QuRGvm6HIz+qSzNcrKqs9nIvLeDMyNs7Dxkrv4jYa22tklXbhE9tymCylV+tMejLcDQSrE59n0bbRIUs2YYOnm4d0i39OvH3DXoSrZuNPkJ6PgoNPG2AAH2AkYdgAquKm1gkUjdY3oG9NE9LoGCnOb2ws+ElGVFp4NlG8y5L9pQ/c9SHc58st/0TDONqct1BErZCG/wQyx14i/xnj4gmsBjiSeQZjKIuDbNdFu3y4zMVMr7L21lGa/0uuxHYj3aYMXMe0CXDBNRYSPMLQ8d+iHvJtWj2HBPfYmHW8Ex21dNSYmXAvWsQHM3qzSWPCEiqkWqb5Gd8hUY5hLiIKoeETRbW/hTKS5UY0OXYR27ALNRsVhQxC6jQhNN8JoyII9R5RXfOEE3OZzAJPtuhJV1JodYSkzvzTN78uDlFWgyuGUP6oeeJRAIBCz6DB2Zxyg+jWGsHLPmvCH9HQTEzrdruQmhL/HKnxmlDYQpGw=
